
import "./globals.css";
import NavBar from "@/components/navBar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`
          body {
            min-height: 100vh;
            margin: 0;
          }
        `}</style>
      </head>
      <body className="overflow-hidden">
        <NavBar />
        {children}
      </body>
    </html>
  );
}